import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LenisProvider from "@/components/LenisProvider";
import AosProvider from "@/components/AosProvider";
import Header from "@/components/Header";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <head>
        <link rel="icon" href="/fav.gif" type="image/gif" />
      </head>
      <body className="min-h-full flex flex-col">
          <LenisProvider>
            <AosProvider>
              <Header />
              {children}
            </AosProvider>
          </LenisProvider>
        </body>
    </html>
  );
}
